# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b819537088f1a74689282be421fa3713f9c79f41c4f2ccd0dbc5735e601b9be2f5c2ca144782ac9bff89300ee3b6a4c88374fe1312651ade9d3107a55a110b92

test:
  secret_key_base: 86139b284f3722e7810d6067388679f43f1cbd0e153818aeea69a61289a786c2e3fbebf3ec6daf580c14365723bebc42391ccb3e7b7d411ca572c5458c63fe2c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
